- alias: Voordeur sensor
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002049ad9
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002049ad9
      to: 'off'
  action:
    service: notify.telegram
    data:
      message: >
        {% if is_state("binary_sensor.door_window_sensor_158d0002049ad9", "on") %}
          Voordeur is open
        {% else %}
          Voordeur is dicht
        {% endif %}

- alias: Achterdeur sensor
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002386484
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002386484
      to: 'off'
  action:
    service: notify.telegram
    data:
      message: >
        {% if is_state("binary_sensor.door_window_sensor_158d0002386484", "on") %}
          Achterdeur is open
        {% else %}
          Achterdeur is dicht
        {% endif %}
