- alias: Notify on boot
  hide_entity: True
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.telegram
    data:
      message: Home Assistant is Online

- alias: Home Assistant news
  hide_entity: True
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.telegram
    data:
      message: 'New update for Home Assistant is now available.'

- alias: Doorbell notification
  hide_entity: True
  trigger:
    platform: event
    event_type: button_pressed
    event_data: { 'entity_id': 'switch.deurbel' }
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xiaomi_gateway_mac
        ringtone_id: 10
        ringtone_vol: 80
    - service: notify.telegram
      data:
        title: HIKvision DS-2CD3345-I
        message: Er wordt aangebeld
        data:
          photo:
            - url: !secret hikvision_image
              username: !secret hikvision_user
              password: !secret hikvision_pwd
              caption: Er wordt aangebeld
    - service: notify.html5
      data:
        title: Voordeur
        message: Er wordt aangebeld
        #data:
        #    image: !secret hikvision_api_image

- alias: Send notification on fire alarm
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.smoke_sensor_158d0001e82161
    from: 'off'
    to: 'on'
  action:
    - service: notify.telegram
      data:
        message: Rook gedetecteerd!
