- platform: yr

# - platform: google_travel_time
#   name: Home to Work
#   api_key: !secret google_api
#   origin: !secret address_home
#   destination: !secret address_work
#   options:
#       mode: driving
#       departure_time: now

# - platform: google_travel_time
#   name: Work to Home
#   api_key: !secret google_api
#   origin: !secret address_work
#   destination: !secret address_home
#   options:
#       mode: driving
#       departure_time: now

- platform: waze_travel_time
  name: Home to Work
  origin: !secret address_home
  destination: !secret address_work
  region: 'EU'

- platform: waze_travel_time
  name: Work to Home
  origin: !secret address_work
  destination: !secret address_home
  region: 'EU'

- platform: nederlandse_spoorwegen
  email: !secret personal_email
  password: !secret ns_password
  routes:
    - name: Capelle aan den IJssel - Rotterdam
      from: Rtd
      to: Cps
    - name: Rotterdam - Capelle aan den IJssel
      from: Cps
      to: Rtd

- platform: speedtest
  minute: 30
  hour:
    - 2
  monitored_conditions:
    - ping
    - download
    - upload

- platform: cert_expiry
  host: !secret hass_url
  name: !secret hass_url

- platform: cert_expiry
  host: !secret thuis_url
  name: !secret thuis_url

- platform: postnl
  username: !secret personal_email
  password: !secret postnl_password

- platform: pi_hole
  host: !secret pihole_url

- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: last_boot
